services:
    dmzx.countdown.listener:
        class: dmzx\countdown\event\listener
        arguments:
            - @controller.helper
            - @template		
        tags:
            - { name: event.listener }
