services:
    dmzx.countdown.admin.controller:
        class: dmzx\countdown\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@request'
    dmzx.countdown.listener:
        class: dmzx\countdown\event\listener
        arguments:
            - '@template'
            - '@config'
        tags:
            - { name: event.listener }
